version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
      args:
        - VITE_API_URL=/api
    image: teksuox/home-frontend:1.0.8
    container_name: vue3_frontend
    ports:
      - "8500:80"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    image: teksuox/home-backend:1.0.8
    container_name: node_backend
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      MONGODB_URI: mongodb://root:6oy6MPHe07XcsH@mongodb:27017/?authSource=admin
      NODE_ENV: production
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 6oy6MPHe07XcsH
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

volumes:
  mongodb_data:

networks:
  app-network:
    driver: bridge
